[package]
name = "f_boom"
version = "0.1.0"
edition = "2024"

[dependencies]
mimalloc     = { version = "0.1", default-features = false }
clap         = { version = "4", features = ["derive"] }
serde        = { version = "1", features = ["derive"] }
toml         = "0.8"
tokio        = { version = "1", features = ["full"] }
tokio-util   = { version = "0.7", features = ["rt", "time"] }
flume        = "0.11"
bytes        = "1"
reqwest      = { version = "0.12", features = ["http2"] }
futures-util = { version = "0.3", default-features = false, features = ["sink", "std", "async-await", "io"] }
tokio-tungstenite = "0.24"
prost        = "0.13"
tonic        = { version = "0.12", features = ["transport"] }
sysinfo      = { version = "0.31", default-features = false, features = ["system"] }
cpu_timer    = "0.1"

[build-dependencies]
tonic-build = "0.12"

[profile.release]
opt-level       = 3
codegen-units   = 1
panic           = "abort"
lto             = "fat"
debug           = false
overflow-checks = false